### ISSUE TITLE
Cannot config password 

### ISSUE THREAD

**Issue by suwitlam-dev** [wso2-extensions/esb-connector-redis#22]
**Description:**

Cannot connect to Redis Server that require password.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Cenos7 amd64

**Steps to reproduce:**
Drag drop redis connector via EI tooling into sequence flow and try to set property password.
<redis.init>
                <redisHost>localhost</redisHost>
                <redisPort>6379</redisPort>
                <redisTimeout>3000</redisTimeout>
</redis.init>

**Related Issues:**

**Comment by JBeanny** [comment]
hello sir , did you find the solution for this yet ? 
it does not work for me although I used <redisConnectionURI></redisConnectionURI>

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/micro-integrator/issues/3486
